### ISSUE TITLE
Use random database name in test databases

### ISSUE THREAD

**Issue by pabarcgar** [EBIvariation/eva-tools#15]
Currently, VariantExporterTestDB class loads the test databases using a _mongorestore_ command not specifying the database name. This may not work in some systems ( https://jira.mongodb.org/browse/TOOLS-620), making the tests fail.

To solve that we should:

- Add the _--db <database>_ parameter to the _mongorestore_ command
- Use a random database name each time the test is executed, to avoid overwriting any existing database
- Create a Junit Rule (similar to https://github.com/EBIvariation/eva-pipeline/blob/develop/src/test/java/uk/ac/ebi/eva/test/rules/TemporaryMongoRule.java ) to use those DBs in the tests. Any useful  code in VariantExporterTestDB can be reused, and that class should be deleted if it is not needed after implementing the Rule.

**Comment by tcezard** [comment]
This issue seems outdated: closing
